### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by billmn** [luke-nehemedia/craft-emailobfuscator#9]
Hi Lucas,
are you planning to add support for Craft 4?

Thank you!

**Comment by luke-nehemedia** [comment]
I cannot give a final answer. I am right now thinking about this and will probably make a decision this weekend. I will keep you (and the doc) updated.

**Comment by billmn** [comment]
Ok, thank you!

**Comment by pimago** [comment]
Any news about your decision?

**Comment by justinholtweb** [comment]
Also awaiting a decision on the future of this plugin. We have several sites where this is the only plugin left not ready for Craft 4. Thanks for your work on this plugin to date! Looking forward to your update.

**Comment by luke-nehemedia** [comment]
I am still undecided.

If I would port it to Craft4 I would want to rewrite it to support project config etc. 
However, since my life situation changed, I do not have a lot of spare time to spend on this. Therefore I was considering changing the plugin to a paid one (for a really small amount) and then really putting the time in re-writing the plugin during June. 

However, there is [another plugin](https://github.com/miranj/craft-obfuscator) from miranj that basically has the same functionality. I reached out to the developer and he is planning to update the plugin to Craft4. 

I am, however, curious to hear whether this alternative solves the issue for you guys or not.

**Comment by luke-nehemedia** [comment]
As already mentioned I won't update this plugin. I recommend using [Craft-Obfuscator](https://github.com/miranj/craft-obfuscator) instead.

I have just updates the README.md and included a module that allows to use the same twig tag with [Craft-Obfuscator](https://github.com/miranj/craft-obfuscator). I hope this will make the transition easier.
